import type { Database, RecipeValidationResult } from "./types.js";
// Generated by scripts/compile-validator.mjs (uses @ts-nocheck so runtime-typed any is fine here).
// We type the imported function locally to keep core/ free of explicit `any`.
interface CompiledValidator { (data: unknown): boolean; errors?: Array<{ instancePath?: string; keyword?: string; message?: string }> | null; }
import { validateRecipe as schemaValidateImported } from "./validator.generated.js";
const schemaValidate: CompiledValidator = schemaValidateImported as unknown as CompiledValidator;

const SUPPORTED_MAJOR = 1;

export function validateRecipe(input: unknown, db?: Database): RecipeValidationResult {
  const issues: RecipeValidationResult["issues"] = [];

  // Layer 1: schema validation (precompiled ajv)
  const ok = schemaValidate(input);
  if (!ok) {
    for (const e of (schemaValidate.errors ?? [])) {
      issues.push({
        path: e.instancePath || "/",
        code: e.keyword === "additionalProperties" || e.keyword === "not" ? "forbidden_property_name" : "schema_violation",
        message: e.message ?? "schema violation",
      });
    }
    return { valid: false, issues };
  }

  const recipe = input as { schema_version?: string; target_loaf_g?: number; items?: Array<{ ingredient_id?: string; grams?: number; bakers_pct?: number }> };

  // Layer 2: schema-version major-mismatch
  const sv = recipe.schema_version ?? "";
  const major = parseInt(sv.split(".")[0] ?? "0", 10);
  if (major !== SUPPORTED_MAJOR) {
    issues.push({ path: "/schema_version", code: "unsupported_schema_version", message: `Recipe schema_version ${sv} not supported by this library (expected ${SUPPORTED_MAJOR}.x).` });
    return { valid: false, issues };
  }

  // Layer 3: cross-reference checks (when db is provided)
  if (db && recipe.items) {
    const known = new Set([...db.ingredients.map((i) => i.id), ...db.flours.map((f) => f.id)]);
    for (let idx = 0; idx < recipe.items.length; idx++) {
      const item = recipe.items[idx]!;
      if (!known.has(item.ingredient_id ?? "")) {
        issues.push({ path: `/items/${idx}/ingredient_id`, code: "unknown_ingredient_id", message: `Unknown ingredient_id: ${item.ingredient_id}` });
      }
    }
  }

  // Layer 4: mode-B quantity check
  if (recipe.target_loaf_g != null && recipe.items) {
    for (let idx = 0; idx < recipe.items.length; idx++) {
      const item = recipe.items[idx]!;
      if (item.grams == null && item.bakers_pct == null) {
        issues.push({ path: `/items/${idx}`, code: "item_missing_quantity", message: "In mode B (target_loaf_g set), each item must have grams or bakers_pct." });
      }
    }
  }

  return { valid: issues.length === 0, issues };
}
