import type { Database, RecipeValidationResult } from "./types.js";
import { isValidUid } from "./uid.js";
// Generated by scripts/compile-validator.mjs (uses @ts-nocheck so runtime-typed any is fine here).
// We type the imported function locally to keep core/ free of explicit `any`.
interface CompiledValidator { (data: unknown): boolean; errors?: Array<{ instancePath?: string; keyword?: string; message?: string }> | null; }
import { validateRecipe as schemaValidateImported } from "./validator.generated.js";
const schemaValidate: CompiledValidator = schemaValidateImported as unknown as CompiledValidator;

const SUPPORTED_MAJOR = 2;

export function validateRecipe(input: unknown, db?: Database): RecipeValidationResult {
  const issues: RecipeValidationResult["issues"] = [];

  // Layer 1: schema validation (precompiled ajv)
  const ok = schemaValidate(input);
  if (!ok) {
    for (const e of (schemaValidate.errors ?? [])) {
      issues.push({
        path: e.instancePath || "/",
        code: e.keyword === "additionalProperties" || e.keyword === "not" ? "forbidden_property_name" : "schema_violation",
        message: e.message ?? "schema violation",
      });
    }
    // After collecting schema issues, also run uid checks so that format/uniqueness
    // codes are emitted even when the schema validator catches the pattern violation.
    // Only do this if the input looks structurally like a recipe (has items array).
    const maybeRecipe = input as { schema_version?: unknown; items?: unknown };
    if (Array.isArray(maybeRecipe.items)) {
      const rawItems = maybeRecipe.items as Array<{ uid?: unknown }>;
      const seenUids = new Map<string, number>();
      for (let i = 0; i < rawItems.length; i++) {
        const rawItem = rawItems[i]!;
        if (typeof rawItem.uid !== "string" || !isValidUid(rawItem.uid)) {
          issues.push({
            path: `/items/${i}/uid`,
            code: "invalid_item_uid_format",
            message: `Item uid "${typeof rawItem.uid === "string" ? rawItem.uid : ""}" does not match ^[A-Za-z0-9_-]{8,16}$.`,
          });
        } else if (seenUids.has(rawItem.uid)) {
          issues.push({
            path: `/items/${i}/uid`,
            code: "duplicate_item_uid",
            message: `Item uid "${rawItem.uid}" duplicates item at index ${seenUids.get(rawItem.uid)}.`,
          });
        } else {
          seenUids.set(rawItem.uid, i);
        }
      }
    }
    return { valid: false, issues };
  }

  const recipe = input as {
    schema_version?: string;
    target_loaf_g?: number;
    items?: Array<{ uid?: string; ingredient_id?: string; grams?: number; bakers_pct?: number }>;
  };

  // Layer 2: schema-version major-mismatch
  const sv = recipe.schema_version ?? "";
  const major = parseInt(sv.split(".")[0] ?? "0", 10);
  if (major !== SUPPORTED_MAJOR) {
    issues.push({ path: "/schema_version", code: "unsupported_schema_version", message: `Recipe schema_version ${sv} not supported by this library (expected ${SUPPORTED_MAJOR}.x).` });
    return { valid: false, issues };
  }

  // Phase 1.4: uid format and uniqueness checks. The schema already validates
  // uid presence and regex per item, but uniqueness across items requires a
  // second pass. We don't short-circuit on the first issue — all uid problems
  // are reported in one pass alongside cross-reference and quantity issues.
  const items = recipe.items ?? [];
  const seen = new Map<string, number>();
  for (let i = 0; i < items.length; i++) {
    const item = items[i]!;
    if (typeof item.uid !== "string" || !isValidUid(item.uid)) {
      issues.push({
        path: `/items/${i}/uid`,
        code: "invalid_item_uid_format",
        message: `Item uid "${item.uid ?? ""}" does not match ^[A-Za-z0-9_-]{8,16}$.`,
      });
      continue;
    }
    if (seen.has(item.uid)) {
      issues.push({
        path: `/items/${i}/uid`,
        code: "duplicate_item_uid",
        message: `Item uid "${item.uid}" duplicates item at index ${seen.get(item.uid)}.`,
      });
    } else {
      seen.set(item.uid, i);
    }
  }

  // Layer 3: cross-reference checks (when db is provided)
  if (db && recipe.items) {
    const known = new Set([...db.ingredients.map((i) => i.id), ...db.flours.map((f) => f.id)]);
    for (let idx = 0; idx < recipe.items.length; idx++) {
      const item = recipe.items[idx]!;
      if (!known.has(item.ingredient_id ?? "")) {
        issues.push({ path: `/items/${idx}/ingredient_id`, code: "unknown_ingredient_id", message: `Unknown ingredient_id: ${item.ingredient_id}` });
      }
    }
  }

  // Layer 4: mode-B quantity check
  if (recipe.target_loaf_g != null && recipe.items) {
    for (let idx = 0; idx < recipe.items.length; idx++) {
      const item = recipe.items[idx]!;
      if (item.grams == null && item.bakers_pct == null) {
        issues.push({ path: `/items/${idx}`, code: "item_missing_quantity", message: "In mode B (target_loaf_g set), each item must have grams or bakers_pct." });
      }
    }
  }

  return { valid: issues.length === 0, issues };
}
